

services:
  db:
    image: 'postgres:18.1-alpine3.22'
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: lexford_db
    # ports:
    #   - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d lexford_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: .
    container_name: lexford-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 9000:3000
    volumes:
      - ./uploads:/usr/src/app/uploads
    environment:
      DATABASE_URL: postgresql://devuser:devpassword@db:5432/lexford_db

volumes:
  postgres_data: